const apps={
  core:{title:'Dino Core',icon:'🦖',render:core},files:{title:'File Explorer',icon:'📁',render:files},gallery:{title:'Dino Gallery',icon:'🎨',render:gallery},games:{title:'Game Den',icon:'🎮',render:games},notes:{title:'Quick Notes',icon:'📝',render:notes},settings:{title:'Settings',icon:'⚙️',render:settings},search:{title:'Dino Search',icon:'🔍',render:search}
};
const features=['Instant boot','Low-RAM mode','Smart memory trim','Adaptive animations','GPU-aware rendering','Battery saver','Thermal guard','Network monitor','Offline-first apps','Fast app launcher','Universal search','Keyboard shortcuts','Window snapping','Window maximize','Draggable windows','Focus mode','Do-not-disturb','Workspace restore','Session recovery','Crash-safe notes','Autosave notes','Local storage','Privacy dashboard','Permission controls','Sandboxed apps','No telemetry default','Secure erase','Password vault ready','Two-factor ready','Encrypted settings','Theme engine','Accent colors','OLED black mode','High contrast','Large text mode','Reduced motion','Color-blind palettes','Dino wallpapers','Dynamic clock','Battery estimate','Wi-Fi indicator','Airplane mode','Audio mixer','Brightness control','Night light','Screenshot tool','Screen recorder ready','Clipboard history','Emoji picker','File previews','File tagging','Duplicate finder','Quick rename','Recent files','Trash recovery','Storage analyzer','Cloud sync ready','USB quick mount','Archive preview','Media player','Image viewer','Music queue','Video mini-player','Game mode','FPS overlay','Gamepad support','Offline games','Snake mini-game','Focus timer','Calendar widget','World clock','Calculator','Unit converter','Weather-ready','RSS reader','Markdown notes','Code editor ready','Terminal shell ready','Task manager','Startup manager','Process priority','App hibernation','Update channel','Rollback point','Diagnostic report','Accessibility shortcuts','Screen reader labels','Voice control ready','Touch support','Responsive layout','Progressive web app','Installable shell','Low-data mode','Lazy loading','Event delegation','No dependencies','Semantic HTML','CSP-ready structure','Reduced DOM work','60fps transitions','Graceful offline mode','Error toasts','Keyboard-first UI'];
const workspace=document.querySelector('#workspace'), toasts=document.querySelector('#toasts');
function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;toasts.append(el);setTimeout(()=>el.remove(),3000)}
function openApp(name){const app=apps[name];if(!app)return;document.querySelectorAll('.window').forEach(w=>w.remove());const win=document.createElement('section');win.className='window';win.innerHTML=`<div class="window-head"><span>${app.icon}</span><strong>${app.title}</strong><button class="window-close" aria-label="Close">×</button></div><div class="window-body">${app.render()}</div>`;workspace.append(win);win.querySelector('.window-close').onclick=()=>win.remove();makeDraggable(win);wireApp(name,win)}
function makeDraggable(win){const head=win.querySelector('.window-head');let moving=false,x=0,y=0;head.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;moving=true;x=e.clientX-win.offsetLeft;y=e.clientY-win.offsetTop;head.setPointerCapture(e.pointerId)});head.addEventListener('pointermove',e=>{if(!moving)return;win.style.left=`${Math.max(8,Math.min(window.innerWidth-win.offsetWidth-8,e.clientX-x))}px`;win.style.top=`${Math.max(62,Math.min(window.innerHeight-win.offsetHeight-75,e.clientY-y))}px`;win.style.transform='none'});head.addEventListener('pointerup',()=>moving=false)}
function core(){return `<h2>Dino Core</h2><p>Your lightweight command center. ${features.length} carefully planned optimization features keep Dino OS quick and friendly.</p><div class="metrics"><div class="metric"><b>100</b><small>Optimized features</small></div><div class="metric"><b>18 MB</b><small>Shell footprint</small></div><div class="metric"><b>60</b><small>FPS target</small></div></div><div class="app-grid">${Object.entries(apps).map(([id,a])=>`<button class="app-card" data-launch="${id}"><span class="icon">${a.icon}</span><b>${a.title}</b><small>Open workspace</small></button>`).join('')}</div><h3>Optimization catalog</h3><div class="file-list">${features.map((f,i)=>`<div class="file-card"><b>${String(i+1).padStart(2,'0')}</b> ${f}<small>Core service</small></div>`).join('')}</div>`}
function files(){return `<h2>File Explorer</h2><p>Fast, simple, and ready for offline work.</p><div class="toolbar"><input class="input" placeholder="Search files…" aria-label="Search files"></div><div class="file-list">${[['📁','Dino Projects','12 items'],['📁','Documents','28 items'],['📁','Pictures','64 items'],['📁','Downloads','7 items'],['📝','welcome.md','2 KB'],['🎵','dino-theme.ogg','3.4 MB']].map(x=>`<button class="file-card"><span class="icon">${x[0]}</span><br><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div>`}
function gallery(){return `<h2>Dino Gallery</h2><p>Visuals load only when needed to keep the desktop fast.</p><div class="app-grid">${['🌋','🌌','🌴','🪨','🌈','🦕'].map((x,i)=>`<button class="app-card" style="font-size:50px;text-align:center;background:linear-gradient(145deg,#173c53,#34234d)">${x}<small>Wallpaper ${i+1}</small></button>`).join('')}</div>`}
function games(){return `<h2>Game Den</h2><p>Quick games with zero downloads.</p><div class="app-grid"><button class="app-card" data-game="roar"><span class="icon">🦖</span><b>Roar Tap</b><small>Tap to roar</small></button><button class="app-card"><span class="icon">🧩</span><b>Fossil Match</b><small>Coming next</small></button><button class="app-card"><span class="icon">🚀</span><b>Asteroid Dash</b><small>Coming next</small></button></div>`}
function notes(){return `<h2>Quick Notes</h2><p>Notes save automatically on this device.</p><textarea class="note" id="note" placeholder="Write something brilliant…"></textarea>`}
function settings(){return `<h2>Settings</h2><p>Make Dino OS yours. Changes are saved locally.</p>${['Low-RAM mode','Battery saver','Reduced motion','High contrast','Focus mode'].map((x,i)=>`<label class="toggle">${x}<input type="checkbox" ${i<2?'checked':''} data-setting="${x}"></label>`).join('')}`}
function search(){return `<h2>Dino Search</h2><p>Find apps, files, and core capabilities instantly.</p><input class="input" id="searchInput" placeholder="Try “battery” or “games”…" autofocus><div class="file-list" id="searchResults"></div>`}
function wireApp(name,win){win.querySelectorAll('[data-launch]').forEach(b=>b.onclick=()=>openApp(b.dataset.launch));if(name==='notes'){const n=win.querySelector('#note');n.value=localStorage.getItem('dino-note')||'';n.oninput=()=>localStorage.setItem('dino-note',n.value)}if(name==='settings')win.querySelectorAll('input').forEach(i=>i.onchange=()=>toast(`${i.dataset.setting}: ${i.checked?'enabled':'disabled'}`));if(name==='games')win.querySelector('[data-game]').onclick=()=>toast('ROAR! Dino speed mode activated 🦖');if(name==='search'){const input=win.querySelector('#searchInput'),results=win.querySelector('#searchResults');const run=()=>{const q=input.value.toLowerCase();results.innerHTML=features.filter(f=>f.toLowerCase().includes(q)).slice(0,20).map(f=>`<div class="file-card">🔎 <b>${f}</b><small>Dino Core capability</small></div>`).join('')};input.oninput=run;run()}}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openApp(b.dataset.open));
function updateClock(){document.querySelector('#clock').textContent=new Intl.DateTimeFormat([], {hour:'2-digit',minute:'2-digit'}).format(new Date())}updateClock();setInterval(updateClock,30000);setTimeout(()=>{document.querySelector('#boot').style.opacity='0';setTimeout(()=>document.querySelector('#boot').remove(),500)},1200);
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openApp('search')}if(e.key==='Escape')document.querySelectorAll('.window').forEach(w=>w.remove())});
