/* DinoHub is an original, independent feature layer inspired by common reader workflows. */
(() => {
  const sample = [
    {id:'dino-001',title:'Dino Quest',author:'Dino Studio',status:'Reading',chapters:24,unread:6,cover:'🦖',source:'Dino Demo Source',genres:['Adventure','Fantasy']},
    {id:'dino-002',title:'Moon Fossils',author:'Open Pages',status:'Plan to read',chapters:12,unread:12,cover:'🌙',source:'Open Pages Demo',genres:['Mystery']},
    {id:'dino-003',title:'Cretaceous Café',author:'Dino Studio',status:'Completed',chapters:18,unread:0,cover:'☕',source:'Dino Demo Source',genres:['Slice of life']}
  ];
  const state = { library: JSON.parse(localStorage.getItem('dinohub-library') || 'null') || sample, tab:'library', query:'' };
  const save=()=>localStorage.setItem('dinohub-library',JSON.stringify(state.library));
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const tabs=[['library','📚 Library'],['browse','🌐 Browse'],['downloads','⬇ Downloads'],['history','🕘 History'],['extensions','🧩 Extensions'],['settings','⚙ Reader settings']];
  function shell(){return `<div class="hub-shell"><aside class="hub-sidebar"><div class="hub-logo">📚 <b>DinoHub</b><small>dark reader edition</small></div>${tabs.map(([id,label])=>`<button class="hub-tab ${state.tab===id?'active':''}" data-hub-tab="${id}">${label}</button>`).join('')}<div class="hub-side-note">Original implementation<br>Use licensed or user-owned sources only.</div></aside><div class="hub-main"><div class="hub-toolbar"><input class="input" id="hubSearch" value="${esc(state.query)}" placeholder="Search library and sources…"><button class="hub-action" data-hub-action="import">＋ Import</button><button class="hub-action" data-hub-action="backup">⇩ Backup</button></div><div id="hubContent">${renderTab()}</div></div></div>`}
  function renderTab(){
    if(state.tab==='library') return `<div class="hub-heading"><div><h2>My Library</h2><p>${state.library.length} titles · ${state.library.reduce((n,x)=>n+x.unread,0)} unread chapters</p></div><select class="input hub-sort" id="hubSort"><option>Recently updated</option><option>Title A–Z</option><option>Unread first</option></select></div><div class="hub-grid">${state.library.filter(x=>!state.query||x.title.toLowerCase().includes(state.query.toLowerCase())).map(card).join('')||empty('No titles found')}</div>`;
    if(state.tab==='browse') return `<div class="hub-heading"><div><h2>Browse sources</h2><p>Discover catalog entries from installed, permissioned extensions.</p></div></div><div class="source-banner">🛡️ DinoHub never ships scraped catalogs. Add only sources you are licensed to access.</div><div class="hub-grid">${['Dino Demo Source','Open Pages Demo','Local CBZ / EPUB'].map((x,i)=>`<article class="source-card"><span class="hub-cover">${['🦖','🌌','📦'][i]}</span><h3>${x}</h3><p>${i===2?'Read files you own offline.':'Example extension endpoint'}</p><button class="hub-action" data-demo-source="${esc(x)}">Open source</button></article>`).join('')}</div>`;
    if(state.tab==='downloads') return `<h2>Downloads</h2><p class="muted">Offline chapters are stored locally by your app shell.</p><div class="download-row"><b>Moon Fossils · Chapter 12</b><span class="download-done">Complete</span></div><div class="download-row"><b>Dino Quest · Chapter 19</b><span class="download-progress"><i></i></span><small>72%</small></div>`;
    if(state.tab==='history') return `<h2>Reading history</h2><p class="muted">Your recent reading position stays on this device.</p>${state.library.map(x=>`<div class="history-row"><span class="hub-cover small">${x.cover}</span><b>${x.title}</b><span>Chapter ${Math.max(1,x.chapters-x.unread)} · ${x.status}</span><button class="hub-action" data-read="${x.id}">Continue</button></div>`).join('')}`;
    if(state.tab==='extensions') return `<h2>Extensions</h2><p class="muted">Install JSON manifests for APIs you control or are authorized to use. DinoHub does not execute arbitrary extension code.</p><div class="extension-box"><input class="input" id="manifestUrl" placeholder="https://your-domain.example/extension.json"><button class="hub-action" data-hub-action="install">Install manifest</button></div><div class="extension-card"><b>🦖 Dino Demo Source</b><small>Built-in sample · catalog API · enabled</small></div><div class="extension-card"><b>📦 Local media</b><small>CBZ/EPUB adapter · enabled</small></div>`;
    return `<h2>Reader settings</h2><p class="muted">These preferences are saved locally and applied by the future reader view.</p>${['Continuous vertical reading','Right-to-left page direction','Preload next chapter','Crop white borders','Keep screen awake','Show reading progress'].map((x,i)=>`<label class="hub-toggle">${x}<input type="checkbox" data-reader-setting="${x}" ${i<3?'checked':''}></label>`).join('')}<h3>Theme</h3><div class="theme-pills"><button class="theme-pill">🌑 Obsidian</button><button class="theme-pill">🌌 Midnight</button><button class="theme-pill">🌋 Volcano</button></div>`;
  }
  function card(x){return `<article class="hub-card"><button class="hub-cover" data-read="${x.id}">${x.cover}</button><div class="hub-card-body"><h3>${esc(x.title)}</h3><p>${esc(x.author)} · ${x.chapters} chapters</p><div class="hub-tags">${x.genres.map(g=>`<span>${esc(g)}</span>`).join('')}</div><div class="hub-card-foot"><small>${x.unread?x.unread+' unread':'Up to date'}</small><button class="hub-action" data-read="${x.id}">${x.unread?'Read':'Open'}</button></div></div></article>`}
  function empty(x){return `<div class="hub-empty">🦕<h3>${x}</h3><p>Try another search or browse a source.</p></div>`}
  function refresh(win){win.querySelector('.window-body').innerHTML=shell();wire(win)}
  function wire(win){const body=win.querySelector('.window-body');body.querySelectorAll('[data-hub-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.hubTab;refresh(win)});const search=body.querySelector('#hubSearch');if(search)search.oninput=()=>{state.query=search.value;const c=body.querySelector('#hubContent');if(state.tab==='library')c.innerHTML=renderTab()};body.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>{const x=state.library.find(y=>y.id===b.dataset.read);if(x){x.unread=Math.max(0,x.unread-1);save();alert(`DinoHub reader placeholder\n\n${x.title}\nNext chapter ready.\n\nConnect a licensed source adapter to load pages.`);refresh(win)}});body.querySelectorAll('[data-demo-source]').forEach(b=>b.onclick=()=>{state.tab='library';state.library.push({id:'demo-'+Date.now(),title:b.dataset.demoSource+' sample',author:'Authorized demo',status:'Plan to read',chapters:3,unread:3,cover:'📖',source:b.dataset.demoSource,genres:['Demo']});save();refresh(win)});body.querySelector('[data-hub-action="backup"]')?.addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state.library,null,2)],{type:'application/json'}));a.download='dinohub-library.json';a.click()});body.querySelector('[data-hub-action="import"]')?.addEventListener('click',()=>alert('Import supports a DinoHub JSON backup in the next storage update.'));body.querySelector('[data-hub-action="install"]')?.addEventListener('click',()=>alert('Manifest validation is intentionally restricted to safe JSON APIs. Do not install untrusted extensions.'))}
  function render(){return shell()}
  apps.dinohub={title:'DinoHub',icon:'📚',render};
  const originalOpenApp=openApp;
  window.openApp=(name)=>{originalOpenApp(name);if(name==='dinohub'){const win=document.querySelector('.window');if(win)wire(win)}};
})();
