import{store,cover,toast,openReader,findManga}from './app.js';
const app=document.querySelector('#app');let current='manga',query='';
const navItems=[['manga','▦','Manga'],['history','◷','History'],['reader-settings','⚙','Reader settings'],['setting','☷','Setting'],['sources','◉','Sources']];
const nav=()=>navItems.map(([id,icon,label])=>`<button class="nav ${current===id?'active':''}" data-nav="${id}"><span>${icon}</span><label>${label}</label></button>`).join('');
const card=m=>`<article class="card"><div class="cover"><img src="${cover(m)}" alt="${m.title}"><span class="badge">${m.status||'New'}</span></div><h3>${m.title}</h3><p>${m.author} · ${m.chapters||0} chapters</p><button class="btn read" data-read="${m.id}">Read chapter 1</button></article>`;
function manga(){const installed=new Set(store.sources.filter(s=>s.installed).map(s=>s.id));const list=store.library.filter(m=>installed.has(m.sourceId||m.source?.toLowerCase()));const filtered=list.filter(m=>!query||`${m.title} ${m.author}`.toLowerCase().includes(query.toLowerCase()));return `<div class="view-head"><div><h1>Manga</h1><p class="sub">Manga available from installed sources</p></div></div>${filtered.length?`<div class="grid">${filtered.map(card).join('')}</div>`:'<div class="empty">No manga available. Install a source from Sources or Setting.</div>'}`}
function history(){return `<div class="view-head"><div><h1>History</h1><p class="sub">Your read chapters and saved progress</p></div>${store.history.length?'<button class="btn" data-action="clear-history">Clear history</button>':''}</div>${store.history.length?`<div class="history-list">${store.history.map(m=>`<div class="history-row"><img src="${cover(m)}" alt=""><div><b>${m.title}</b><p class="muted">Chapter ${m.chapter} · ${new Date(m.readAt).toLocaleDateString()}</p></div><button class="btn" data-read="${m.id}" data-chapter="${m.chapter}">Continue</button></div>`).join('')}</div>`:'<div class="empty">No reading history yet.</div>'}`}
function readerSettings(){const s=store.settings;return `<div class="view-head"><div><h1>Reader settings</h1><p class="sub">Customize chapter reading</p></div></div><div class="panel">${[['direction','Reading direction','Vertical','Left to right','Right to left'],['fit','Image fitting','Width','Original','Height']].map(([key,label,...opts])=>`<div class="row"><div><b>${label}</b><p class="muted">Choose your preferred layout</p></div><select class="setting" data-setting="${key}">${opts.map(o=>`<option ${s[key]===o?'selected':''}>${o}</option>`).join('')}</select></div>`).join('')}<div class="row"><div><b>Preload next page</b><p class="muted">Load pages faster</p></div><input type="checkbox" class="setting" data-setting="preload" ${s.preload?'checked':''}></div></div>`}
function sourceRow(s){return `<div class="row source-row"><div><b>${s.name}</b><p class="muted">${s.language||'Unknown language'} · ${s.version||'Unknown version'} · ${s.repo||'Repository source'}</p></div><div>${s.installed?'<span class="status">● Installed</span>':'<button class="btn primary" data-install-source="'+s.id+'">Install adapter</button>'}</div></div>`}
function sources(){const sources=store.sources;return `<div class="view-head"><div><h1>Sources</h1><p class="sub">Extensions discovered from your repositories</p></div></div><div class="panel"><h2>Installed and available sources</h2>${sources.length?sources.map(sourceRow).join(''):'<div class="empty">No sources discovered yet. Add a repository in Setting.</div>'}</div><div class="panel"><p class="muted">Paste a Mihon repository in Setting to discover its individual extensions. Installing an extension enables it for the Manga catalog.</p></div>`}
function setting(){return `<div class="view-head"><div><h1>Setting</h1><p class="sub">Add Mihon extension repositories</p></div></div><div class="panel"><h2>Paste extension repository</h2><p class="muted">Use a repository URL such as a GitHub repository or its raw/GitHub Pages URL. DinoReaders will look for repo.json, index.json, and index.min.json, then show every extension separately in Sources.</p><form id="repo-form" class="repo-form"><input class="input" name="repo" type="url" placeholder="https://github.com/owner/extension-repo" required><button class="btn primary">Discover sources</button></form><p id="repo-status" class="muted"></p></div><div class="panel"><h2>How installation works</h2><p class="muted">Discovery reads public extension metadata. An individual source is not enabled until you press Install adapter on the Sources page. A browser cannot execute Mihon Android APK/Kotlin extensions directly; a compatible web adapter must provide browser-safe API behavior and obey the source’s license, CORS, rate limits, and terms.</p></div>`}
function view(){const body=current==='manga'?manga():current==='history'?history():current==='reader-settings'?readerSettings():current==='sources'?sources():setting();app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand">Dino<span>Readers</span></div><input class="search" value="${query}" placeholder="Search manga or author…" aria-label="Search manga"></header><div class="layout"><aside class="sidebar">${nav()}</aside><main class="content">${body}</main></div></div>`;bind()}
function possibleManifests(url){const u=url.replace(/\/$/,'');if(/raw\.githubusercontent\.com|github\.io/.test(u))return[`${u}/repo.json`,`${u}/index.json`,`${u}/index.min.json`];const m=u.match(/github\.com\/([^/]+)\/([^/#]+)/i);if(!m)return[`${u}/repo.json`,`${u}/index.json`,`${u}/index.min.json`];const owner=m[1],repo=m[2].replace(/\.git$/,'');return['main','master'].flatMap(branch=>['repo.json','index.json','index.min.json'].map(file=>`https://raw.githubusercontent.com/${owner}/${repo}/${branch}/${file}`));}
function extensionList(data){const raw=Array.isArray(data)?data:data.extensions||data.sources||data.items||data.apps||data;return Array.isArray(raw)?raw:Object.entries(raw||{}).map(([id,value])=>({id,...value}));}
function normaliseExtensions(data,repo){return extensionList(data).filter(x=>x&&typeof x==='object').map((x,i)=>({id:String(x.id||x.pkg||x.packageName||`source-${Date.now()}-${i}`),name:x.name||x.title||x.id||`Source ${i+1}`,version:x.version||x.ver||'Unknown',language:x.lang||x.language||x.languages?.[0]||'Unknown language',icon:x.icon||x.iconUrl,repo,installed:false,status:'Available'}));}
async function discover(url){const status=document.querySelector('#repo-status');status.textContent='Fetching repository index…';let lastError='';for(const manifest of possibleManifests(url)){try{const response=await fetch(manifest,{headers:{Accept:'application/json'}});if(!response.ok)continue;const data=await response.json();const found=normaliseExtensions(data,url);if(!found.length)throw Error('No extensions found in manifest');const existing=new Map(store.sources.map(s=>[s.id,s]));found.forEach(s=>existing.set(s.id,{...s,...existing.get(s.id)}));store.sources=[...existing.values()];status.textContent=`Found ${found.length} source${found.length===1?'':'s'}. Open Sources to install them.`;toast(`${found.length} sources discovered`);return}catch(error){lastError=error.message}}status.textContent=`Could not read a compatible repository index. ${lastError||'Check the URL and CORS permissions.'}`;toast('Repository discovery failed')}
function bind(){document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>{current=x.dataset.nav;view()});const search=document.querySelector('.search');search.oninput=e=>{query=e.target.value;view();document.querySelector('.search')?.focus()};document.querySelectorAll('[data-read]').forEach(x=>x.onclick=()=>openReader(findManga(x.dataset.read),Number(x.dataset.chapter||1)));document.querySelector('[data-action="clear-history"]')?.addEventListener('click',()=>{store.history=[];view()});document.querySelectorAll('.setting').forEach(x=>x.onchange=()=>{store.settings={...store.settings,[x.dataset.setting]:x.type==='checkbox'?x.checked:x.value};toast('Reader settings saved')});document.querySelector('#repo-form')?.addEventListener('submit',async e=>{e.preventDefault();const url=new FormData(e.target).get('repo').trim();await discover(url);e.target.reset();view()});document.querySelectorAll('[data-install-source]').forEach(x=>x.onclick=()=>{const id=x.dataset.installSource;store.sources=store.sources.map(s=>s.id===id?{...s,installed:true,status:'Installed'}:s);toast('Source adapter installed');current='sources';view()})}
view();
