import{store,cover,toast,openReader,findManga}from './app.js';
const app=document.querySelector('#app');let current='manga',query='';
const navItems=[['manga','▦','Manga'],['history','◷','History'],['reader-settings','⚙','Reader settings'],['setting','☷','Setting'],['sources','◉','Sources']];
const nav=()=>navItems.map(([id,icon,label])=>`<button class="nav ${current===id?'active':''}" data-nav="${id}"><span>${icon}</span><label>${label}</label></button>`).join('');
const card=m=>`<article class="card"><div class="cover"><img src="${cover(m)}" alt="${m.title}"><span class="badge">${m.status||'New'}</span></div><h3>${m.title}</h3><p>${m.author} · ${m.chapters||0} chapters</p><button class="btn read" data-read="${m.id}">Read chapter 1</button></article>`;
function manga(){const installed=new Set(store.sources.filter(s=>s.installed).map(s=>s.id));const list=store.library.filter(m=>installed.has(m.sourceId||m.source?.toLowerCase()));const filtered=list.filter(m=>!query||`${m.title} ${m.author}`.toLowerCase().includes(query.toLowerCase()));return `<div class="view-head"><div><h1>Manga</h1><p class="sub">Manga available from installed sources</p></div></div>${filtered.length?`<div class="grid">${filtered.map(card).join('')}</div>`:'<div class="empty">No manga available. Install a source from Sources or Setting.</div>'}`}
function history(){return `<div class="view-head"><div><h1>History</h1><p class="sub">Your read chapters and saved progress</p></div>${store.history.length?'<button class="btn" data-action="clear-history">Clear history</button>':''}</div>${store.history.length?`<div class="history-list">${store.history.map(m=>`<div class="history-row"><img src="${cover(m)}" alt=""><div><b>${m.title}</b><p class="muted">Chapter ${m.chapter} · ${new Date(m.readAt).toLocaleDateString()}</p></div><button class="btn" data-read="${m.id}" data-chapter="${m.chapter}">Continue</button></div>`).join('')}</div>`:'<div class="empty">No reading history yet.</div>'}`}
function readerSettings(){const s=store.settings;return `<div class="view-head"><div><h1>Reader settings</h1><p class="sub">Customize chapter reading</p></div></div><div class="panel">${[['direction','Reading direction','Vertical','Left to right','Right to left'],['fit','Image fitting','Width','Original','Height']].map(([key,label,...opts])=>`<div class="row"><div><b>${label}</b><p class="muted">Choose your preferred layout</p></div><select class="setting" data-setting="${key}">${opts.map(o=>`<option ${s[key]===o?'selected':''}>${o}</option>`).join('')}</select></div>`).join('')}<div class="row"><div><b>Preload next page</b><p class="muted">Load pages faster</p></div><input type="checkbox" class="setting" data-setting="preload" ${s.preload?'checked':''}></div></div>`}
function sourceRow(s){return `<div class="row source-row"><div><b>${s.name}</b><p class="muted">${s.repo}</p></div><div>${s.installed?'<span class="status">● Installed</span>':'<button class="btn primary" data-install-source="'+s.id+'">Install adapter</button>'}</div></div>`}
function sources(){return `<div class="view-head"><div><h1>Sources</h1><p class="sub">All catalogs and their adapter status</p></div></div><div class="panel"><h2>Available sources</h2>${store.sources.map(sourceRow).join('')}</div><div class="panel"><p class="muted">Only installed adapters contribute manga to the Manga section. Add repositories from Setting.</p></div>`}
function setting(){return `<div class="view-head"><div><h1>Setting</h1><p class="sub">Add extension repositories and create adapters</p></div></div><div class="panel"><h2>Paste extension repository</h2><p class="muted">Paste a public Mihon-style extension repository URL. It will be added as an uninstalled source first.</p><form id="repo-form" class="repo-form"><input class="input" name="repo" type="url" placeholder="https://github.com/owner/extension-repo" required><button class="btn primary">Add source</button></form></div><div class="panel"><h2>AI adapter assistant</h2><p class="muted">The adapter is created only when you press Install adapter on the Sources page. This frontend demo records the repository locally; a production AI adapter needs a secure backend and must respect licenses, CORS, rate limits, and terms.</p></div>`}
function view(){const body=current==='manga'?manga():current==='history'?history():current==='reader-settings'?readerSettings():current==='sources'?sources():setting();app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand">Dino<span>Readers</span></div><input class="search" value="${query}" placeholder="Search manga or author…" aria-label="Search manga"></header><div class="layout"><aside class="sidebar">${nav()}</aside><main class="content">${body}</main></div></div>`;bind()}
function bind(){document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>{current=x.dataset.nav;view()});const search=document.querySelector('.search');search.oninput=e=>{query=e.target.value;view();document.querySelector('.search')?.focus()};document.querySelectorAll('[data-read]').forEach(x=>x.onclick=()=>openReader(findManga(x.dataset.read),Number(x.dataset.chapter||1)));document.querySelector('[data-action="clear-history"]')?.addEventListener('click',()=>{store.history=[];view()});document.querySelectorAll('.setting').forEach(x=>x.onchange=()=>{store.settings={...store.settings,[x.dataset.setting]:x.type==='checkbox'?x.checked:x.value};toast('Reader settings saved')});document.querySelector('#repo-form')?.addEventListener('submit',e=>{e.preventDefault();const url=new FormData(e.target).get('repo').trim();const match=url.match(/github\.com\/([^/]+)\/([^/#]+)/i);const name=match?match[2].replace(/[-_]/g,' '):'Custom source';const id=`custom-${Date.now()}`;store.sources=[...store.sources,{id,name:name.replace(/\b\w/g,c=>c.toUpperCase()),repo:url,status:'Waiting for install',installed:false}];toast('Source added — install it from Sources');e.target.reset();view()});document.querySelectorAll('[data-install-source]').forEach(x=>x.onclick=()=>{const id=x.dataset.installSource;store.sources=store.sources.map(s=>s.id===id?{...s,installed:true,status:'Installed'}:s);toast('AI adapter installed');current='sources';view()})}
view();
