import{store,cover,toast,openReader,findManga}from './app.js';
const app=document.querySelector('#app');let current='manga',query='';
const PREBUILT_REPO='https://github.com/keiyoushi/extensions';
const navItems=[['manga','▦','Manga'],['history','◷','History'],['reader-settings','⚙','Reader settings'],['setting','☷','Setting'],['sources','◉','Sources']];
const nav=()=>navItems.map(([id,icon,label])=>`<button class="nav ${current===id?'active':''}" data-nav="${id}"><span>${icon}</span><label>${label}</label></button>`).join('');
const card=m=>`<article class="card"><div class="cover"><img src="${cover(m)}" alt="${m.title}"><span class="badge">${m.status||'New'}</span></div><h3>${m.title}</h3><p>${m.author} · ${m.chapters||0} chapters</p><button class="btn read" data-read="${m.id}">Read chapter 1</button></article>`;
function manga(){const installed=new Set(store.sources.filter(s=>s.installed).map(s=>s.id));const list=store.library.filter(m=>installed.has(m.sourceId||m.source?.toLowerCase()));const filtered=list.filter(m=>!query||`${m.title} ${m.author}`.toLowerCase().includes(query.toLowerCase()));return `<div class="view-head"><div><h1>Manga</h1><p class="sub">Manga available from installed sources</p></div></div>${filtered.length?`<div class="grid">${filtered.map(card).join('')}</div>`:'<div class="empty">No manga available. Open Sources and install a source adapter.</div>'}`}
function history(){return `<div class="view-head"><div><h1>History</h1><p class="sub">Your read chapters and saved progress</p></div>${store.history.length?'<button class="btn" data-action="clear-history">Clear history</button>':''}</div>${store.history.length?`<div class="history-list">${store.history.map(m=>`<div class="history-row"><img src="${cover(m)}" alt=""><div><b>${m.title}</b><p class="muted">Chapter ${m.chapter} · ${new Date(m.readAt).toLocaleDateString()}</p></div><button class="btn" data-read="${m.id}" data-chapter="${m.chapter}">Continue</button></div>`).join('')}</div>`:'<div class="empty">No reading history yet.</div>'}`}
function readerSettings(){const s=store.settings;return `<div class="view-head"><div><h1>Reader settings</h1><p class="sub">Customize chapter reading</p></div></div><div class="panel">${[['direction','Reading direction','Vertical','Left to right','Right to left'],['fit','Image fitting','Width','Original','Height']].map(([key,label,...opts])=>`<div class="row"><div><b>${label}</b><p class="muted">Choose your preferred layout</p></div><select class="setting" data-setting="${key}">${opts.map(o=>`<option ${s[key]===o?'selected':''}>${o}</option>`).join('')}</select></div>`).join('')}<div class="row"><div><b>Preload next page</b><p class="muted">Load pages faster</p></div><input type="checkbox" class="setting" data-setting="preload" ${s.preload?'checked':''}></div></div>`}
function sourceRow(s){return `<div class="row source-row"><div><b>${s.name}</b><p class="muted">${s.language||'all'} · ${s.version||'Community'} · ${s.repo||'Repository source'}</p></div><div>${s.installed?'<span class="status">● Installed</span>':'<button class="btn primary" data-install-source="'+s.id+'">Install source</button>'}</div></div>`}
function sources(){const sources=store.sources;return `<div class="view-head"><div><h1>Sources</h1><p class="sub">${sources.length} sources available — install one to show its manga</p></div></div><div class="panel"><h2>Available extensions</h2>${sources.map(sourceRow).join('')}</div><div class="panel"><p class="muted">Preloaded sources come from Keiyoushi. Pasted repository entries will also appear here. Installing a source is required before its manga appears in Manga.</p></div>`}
function setting(){return `<div class="view-head"><div><h1>Setting</h1><p class="sub">Add Mihon extension repositories</p></div></div><div class="panel"><h2>Preinstalled repository</h2><p class="muted">Keiyoushi extensions is preloaded. Sources such as MangaDex and MangaFreak are ready to install.</p><button class="btn" data-nav="sources">Open Sources</button></div><div class="panel"><h2>Paste extension repository</h2><p class="muted">Paste a GitHub, GitHub Pages, raw JSON, or Mihon repository URL. Each discovered extension appears separately in Sources.</p><form id="repo-form" class="repo-form"><input class="input" name="repo" type="url" placeholder="https://github.com/owner/extension-repo" required><button class="btn primary">Discover sources</button></form><p id="repo-status" class="muted"></p></div>`}
function view(){const body=current==='manga'?manga():current==='history'?history():current==='reader-settings'?readerSettings():current==='sources'?sources():setting();app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand">Dino<span>Readers</span></div><input class="search" value="${query}" placeholder="Search manga or author…" aria-label="Search manga"></header><div class="layout"><aside class="sidebar">${nav()}</aside><main class="content">${body}</main></div></div>`;bind()}
function possibleManifests(url){const u=url.replace(/\/$/,'');if(/\.json$/i.test(u))return[u];if(/raw\.githubusercontent\.com|github\.io/.test(u))return[`${u}/index.min.json`,`${u}/index.json`,`${u}/repo.json`];const m=u.match(/github\.com\/([^/]+)\/([^/#]+)/i);if(!m)return[`${u}/index.min.json`,`${u}/index.json`,`${u}/repo.json`];const owner=m[1],repo=m[2].replace(/\.git$/,'');return['repo','main','master'].flatMap(branch=>['index.min.json','index.json','repo.json'].map(file=>branch==='repo'?`https://raw.githubusercontent.com/${owner}/${repo}/repo/${file}`:`https://raw.githubusercontent.com/${owner}/${repo}/${branch}/${file}`));}
function extensionList(data){const raw=Array.isArray(data)?data:data.extensions||data.sources||data.items||data.apps||data;return Array.isArray(raw)?raw:Object.entries(raw||{}).map(([id,value])=>({id,...value}));}
function normaliseExtensions(data,repo){const result=[];extensionList(data).forEach((ext,i)=>{const nested=Array.isArray(ext.sources)&&ext.sources.length?ext.sources:[ext];nested.forEach((source,j)=>{if(!source||typeof source!=='object')return;result.push({id:String(source.id||source.pkg||ext.pkg||`source-${Date.now()}-${i}-${j}`),name:source.name||ext.name||source.title||`Source ${i+1}`,version:ext.version||source.version||'Unknown',language:source.lang||ext.lang||source.language||'all',repo,extension:ext.name&&source.name!==ext.name?ext.name:'',installed:false,status:'Available'});});});return result;}
async function discover(url){const status=document.querySelector('#repo-status');if(status)status.textContent='Fetching extension index…';for(const manifest of possibleManifests(url)){try{const response=await fetch(manifest);if(!response.ok)continue;const found=normaliseExtensions(await response.json(),url);if(!found.length)continue;const map=new Map(store.sources.map(s=>[s.id,s]));found.forEach(s=>map.set(s.id,{...s,...map.get(s.id)}));store.sources=[...map.values()];toast(`${found.length} sources discovered`);current='sources';view();return}catch{}}if(status)status.textContent='Could not read this repository. It may block browser requests (CORS).';toast('No compatible public index found')}
function bind(){document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>{current=x.dataset.nav;view()});const search=document.querySelector('.search');search.oninput=e=>{query=e.target.value;view();document.querySelector('.search')?.focus()};document.querySelectorAll('[data-read]').forEach(x=>x.onclick=()=>openReader(findManga(x.dataset.read),Number(x.dataset.chapter||1)));document.querySelector('[data-action="clear-history"]')?.addEventListener('click',()=>{store.history=[];view()});document.querySelectorAll('.setting').forEach(x=>x.onchange=()=>{store.settings={...store.settings,[x.dataset.setting]:x.type==='checkbox'?x.checked:x.value};toast('Reader settings saved')});document.querySelectorAll('[data-install-source]').forEach(x=>x.onclick=()=>{store.sources=store.sources.map(s=>s.id===x.dataset.installSource?{...s,installed:true,status:'Installed'}:s);toast('Source installed');current='manga';view()});document.querySelector('#repo-form')?.addEventListener('submit',async e=>{e.preventDefault();await discover(new FormData(e.target).get('repo').trim());e.target.reset()})}
view();
